# Generated by Django 4.1.7 on 2023-03-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttonmodel',
            options={'verbose_name': 'Кнопка', 'verbose_name_plural': 'Кнопки'},
        ),
    ]
