# Generated by Django 4.1.7 on 2023-03-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_buttonmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
