# Generated by Django 4.1.7 on 2023-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_usermodel_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Сюжет',
                'verbose_name_plural': 'Сюжет',
            },
        ),
    ]
